name: Docker Image CI

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Login Dockerhub
              env:
                  DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
                  DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

            - name: Build the Docker image
              run: docker build -t solibyeli .
            - name: taging
              run: docker tag solibyeli:latest qudqud97/solibyeli:latest
            - name: Push to Dockerhub
              run: docker push qudqud97/solibyeli:latest

name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull qudqud97/solibyeli:latest
    - name: Delete Old docker container
      run: sudo docker rm -f solibyeli-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:3000 --name solibyeli-container qudqud97/solibyeli
 

